development:
    lang: "pt"
    base: ""
    couchdb: "http://couchdb:5984"
    connect: "http://connect:8080"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://elasticsearch:9200"
    floradata: "http://floradata"
    floradata_url: "http://localhost:8181"
test:
    lang: "pt"
    base: ""
    couchdb: "http://couchdb:5984"
    connect: "http://connect:8080"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://elasticsearch:9200"
    floradata: "http://floradata"
    floradata_url: "http://localhost:8181"
production:
    lang: "pt"
    base: "/checklist"
    couchdb: "http://$HOST/couchdb"
    connect: "http://$HOST/connect"
    connect_url: "http://cncflora.jbrj.gov.br/connect"
    elasticsearch: "http://$HOST/elasticsearch"
    floradata: "http://$HOST/floradata"
    floradata_url: "http://cncflora.jbrj.gov.br/floradata"
    profiles: "http://$HOST/profiles"
    profiles_url: "http://cncflora.jbrj.gov.br/profiles"
