development:
    lang: "pt"
    base: ""
    couchdb: "http://couchdb:5984"
    connect: "http://connect:8080"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://elasticsearch:9200"
    floradata: "http://floradata"
    floradata_url: "http://localhost:8181"
    servicos: "http://servicos.jbrj.gov.br/flora"
test:
    lang: "pt"
    base: ""
    couchdb: "http://couchdb:5984"
    connect: "http://connect:8080"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://elasticsearch:9200"
    floradata: "http://floradata"
    floradata_url: "http://localhost:8181"
    servicos: "http://servicos.jbrj.gov.br/flora"
production:
    lang: "pt"
    base: "/checklist"
    couchdb: 'http://couchdb:5984'
    connect: 'http://connect'
    connect_url: 'http://$HOST/connect'
    elasticsearch: 'http://elasticsearch:9200'
    floradata: "http://floradata"
    floradata_url: "http://$HOST/floradata"
    profiles: "http://profiles"
    profiles_url: "http://$HOST/profiles"
    servicos: "http://servicos.jbrj.gov.br/flora"
