development:
    lang: "pt"
    base: ""
    couchdb: "http://192.168.50.16:5984"
    connect: "http://192.168.50.16:8080"
    connect_url: "http://192.168.50.16:8080"
    elasticsearch: "http://192.168.50.16:9200"
    floradata: "http://192.168.50.16:8181"
    floradata_url: "http://192.168.50.16:8181"
test:
    lang: "pt"
    base: ""
    couchdb: "http://192.168.50.16:5984"
    connect: "http://192.168.50.16:8080"
    connect_url: "http://192.168.50.16:8080"
    elasticsearch: "http://192.168.50.16:9200"
    floradata: "http://192.168.50.16:8181"
    floradata_url: "http://192.168.50.16:8181"
production:
    lang: "pt"
    base: "/checklist"
    couchdb: "http://$HOST/couchdb"
    connect: "http://$HOST/connect"
    connect_url: "http://$HOST/connect"
    elasticsearch: "http://$HOST/elasticsearch"
    floradata: "http://$HOST/floradata"
    floradata_url: "http://$HOST/floradata"
    profiles: "http://$HOST/profiles"
    profiles_url: "http://$HOST/profiles"
