development:
    etcd: "http://192.168.50.16:4001"
    db: "cncflora_occurrence"
    lang: "pt"
    base: ""
test:
    etcd: "http://192.168.50.16:4001"
    lang: "pt"
    db: "taxonomy_test"
    base: ""
production:
    etcd: "http://cncflora.jbrj.gov.br/etcd"
    db: "taxonomy"
    lang: "pt"
    base: "/occurrences"
