development:
    lang: "pt"
    base: ""
    couchdb: "http://192.168.50.16:5984"
    connect: "http://192.168.50.16:8080"
    floradata: "http://192.168.50.16:8001"
    elasticsearch: "http://192.168.50.16:9200"
test:
    lang: "pt"
    base: ""
    couchdb: "http://192.168.50.16:5984"
    connect: "http://192.168.50.16:8080"
    floradata: "http://192.168.50.16:8001"
    elasticsearch: "http://192.168.50.16:9200"
production:
    lang: "pt"
    base: "/checklist"
    couchdb: "http://$HOST/couchdb"
    connect: "http://$HOST/connect"
    floradata: "http://$HOST/floradata"
    elasticsearch: "http://$HOST/elasticsearch"
