development:
    etcd: "http://192.168.50.16:4001"
    lang: "pt"
    base: ""
test:
    etcd: "http://192.168.50.16:4001"
    lang: "pt"
    base: ""
production:
    etcd: "http://cncflora.jbrj.gov.br/etcd"
    lang: "pt"
    base: "/checklist"
