checklist:
    build: .
    ports:
        - 8081:80
    volumes:
        - .:/var/www
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - floradata:floradata
    environment:
        - RACK_ENV=development
elasticsearch:
    image: cncflora/elasticsearch
    name: elasticsearch
    restart: "no"
    ports:
        - "9200"
    volumes:
        - "/var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw"
couchdb:
    image: cncflora/couchdb
    name: couchdb
    restart: "no"
    ports:
        - "5984:5984"
        - "9001"
    volumes:
        - "/var/data/couchdb:/var/lib/couchdb:rw"
    links:
        - "elasticsearch:elasticsearch"
connect:
    image: cncflora/connect
    name: connect
    restart: "no"
    ports:
        - "8080:80"
    volumes:
        - "/var/data/connect:/var/floraconnect:rw"
floradata:
    image: cncflora/floradata
    name: floradata
    restart: "no"
    environment:
        SERVICE_80_CHECK_HTTP: /api/v1/families
    ports:
        - "8181:80"
        - "9005:9001"
