checklist:
    build: .
    ports:
        - 8081:80
    volumes:
        - .:/opt/app
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - floradata:floradata
    environment:
        - RACK_ENV=development
elasticsearch:
    image: cncflora/elasticsearch
    ports:
        - 9200:9200
    volumes:
        - /var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw
couchdb:
    image: cncflora/couchdb
    ports:
        - 5984:5984
        - 9001
    volumes:
        - /var/data/couchdb:/var/lib/couchdb:rw
connect:
    image: cncflora/connect
    ports:
        - 8080:80
    volumes:
        - /var/data/connect:/var/floraconnect:rw
floradata:
    image: cncflora/floradata
    ports:
        - 8181:80
        - 9005:9001
